### ISSUE TITLE
Undefined function ShortPixel\curl_version()

### ISSUE THREAD

**Issue by ecotechie** [short-pixel-optimizer/shortpixel-php#6]
Hi love the service and have it working fine under WordPress.
However, sometimes I want to optimize local files using:
`php cmdShortpixelOptimize.php --apiKey=mykey --folder=afolder`

Here is the output... Looks like it's failing accessing curl, but I have it installed and use it often.

```
5a715dd7d71a9@2018-01-30 22:10:31> Folder has 2 files, 0 optimized, 2 pending, 0 don't need optimization, 0 failed.
PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 32
PHP Notice:  Use of undefined constant CURLOPT_BINARYTRANSFER - assumed 'CURLOPT_BINARYTRANSFER' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 33
PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 34
PHP Notice:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 35
PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 37
PHP Notice:  Use of undefined constant CURLOPT_SSL_VERIFYHOST - assumed 'CURLOPT_SSL_VERIFYHOST' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 38
PHP Notice:  Use of undefined constant CURLOPT_USERAGENT - assumed 'CURLOPT_USERAGENT' in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 39
PHP Fatal error:  Uncaught Error: Call to undefined function ShortPixel\curl_version() in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php:22
Stack trace:
#0 /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php(39): ShortPixel\Client::userAgent()
#1 /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel.php(106): ShortPixel\Client->__construct()
#2 /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Commander.php(149): ShortPixel\ShortPixel::getClient()
#3 /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Commander.php(118): ShortPixel\Commander->execute(true)
#4 /home/sergio/WebD/tools/shortpixel-php-master/lib/cmdShortpixelOptimize.php(124): ShortPixel\Commander->__call('toFiles', Array)
#5 {main}
  thrown in /home/sergio/WebD/tools/shortpixel-php-master/lib/ShortPixel/Client.php on line 22
```

Thanks!

**Comment by short-pixel-optimizer** [comment]
Hi Sergio,

Thanks for your message and sorry for the problem. Indeed it looks like you don't have curl... maybe you use a different PHP from command line? Could you please send me the output of phpinfo() when ran from the command line?

Best regards,
Simon.
